#!/usr/bin/env bash
cd "$(dirname "$0")"
OUTPUT="../../../.github/workflows/ci.yml"
cat <<EOF > $OUTPUT
#############################################################
#   WARNING: automatically generated file, DO NOT CHANGE!   #
#############################################################

# This file was automatically generated by the expand-yaml-anchors tool. The
# source file that generated this one is:
#
#   src/ci/github-actions/ci.dhall
#
# Once you make changes to that file you need to run:
#
#   ./x.py run src/tools/expand-yaml-anchors/
#
# The CI build will fail if the tool is not run after changes to this file.

---
EOF
dhall-to-yaml --file ci.dhall >> $OUTPUT
